In [6]:
import numpy as np

In [21]:
np.__version__

'1.21.5'

In [9]:
np.__path__

['/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/numpy']

In [13]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

In [34]:
arr=np.array([[45,12,34],[43,43,65],[76.23,21]],dtype=np.uint64)
type(arr)

43

In [75]:
print(np.array(10))
arr=np.array([1,2,3,4])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

10
1
(4,)
4
8
32


In [32]:
arr3d=np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]],
                [[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]],
                [[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]]])
print(arr3d.shape)
print(arr3d.ndim)
print(arr3d.size)

array([10, 11, 12, 13])

In [10]:
zeros=np.ones((2,3))
print(zeros)
print(zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [93]:
np.full((4,3),10,dtype=int)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [95]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
np.eye(3,4,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [107]:
np.eye(3,4,k=1,dtype=np.int8)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [115]:
np.fromstring('1 2 3 4',dtype=np.int16,sep=" ")

array([1, 2, 3, 4], dtype=int16)

In [133]:
np.arange(1,10)
print(np.arange(1,10)
.dtype)

int64


In [127]:
np.arange(1,10,0.5,dtype=np.float16)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5], dtype=float16)

In [147]:
np.linspace(1,10)
print(np.linspace(1,10).shape)

(50,)
